name: test-client

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        # stepsはデフォはrme/clientの中で実行する
        working-directory: ./rme/client

    steps:
      - name: チェックアウト
        uses: actions/checkout@v2

      - name: node.js、npm、yarnのインストール
        uses: actions/setup-node@v2
        with:
          node-version: 16.5.x

      - name: ライブラリインストール
        run: |
          cd rme/client
          yarn

      - name: テスト
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rme/client
          yarn test

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        # stepsはデフォはrmeの中で実行する
        working-directory: ./rme

    steps:
      - name: チェックアウト
        uses: actions/checkout@v2

      - name: node.js、npm、yarnのインストール
        uses: actions/setup-node@v2
        with:
          node-version: 16.5.x

      - name: ライブラリインストール
        run: |
          yarn

      - name: テスト
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn test
